spring:
  profiles:
    active:
      - dev
      - properties
      - mybatisplus
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  resources:
    static-locations:
      - file:///${fileupload.base-path}
#  mvc:
#    static-path-pattern: /**
logging:
  level:
    programmer.lp.jk: debug
