server:
  servlet:
    context-path: /jk
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active:
      - dev
      - properties
mybatis-plus:
  type-aliases-package: programmer.lp.jk.pojo
  global-config:
    db-config:
      id-type: auto # 主键自增
